import Head from 'next/head'
import { Inter } from '@next/font/google'
import  Header  from './components/header'
import Pricing from './components/pricing'
import  Features  from './components/features'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Pricing UI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <Header/>
    <Pricing/>
    <Features/>
    </>
  )
}
